### PR TITLE
bugfix - include path to translations

### PR DESCRIPTION
**Pull request by joefitter**
This was causing an error when rendering terms and cookies pages

### CODE REVIEW

**Comment by JoeChapman** [comment]
@joefitter rebase

**Comment by joefitter** [comment]
pssht

**Comment by JoeChapman** [comment]
@joefitter I think these changes have been superceeded, this is now redundant

**Comment by joefitter** [comment]
This is still needed - translations path still isn't defined meaning terms and cookies will be broken

**Comment by JoeChapman** [comment]
Ok, fixy , fixy

**Pull request merged**
